apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-build-jobs
subjects:
- kind: ServiceAccount
  name: {{ include "build-tomo.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: build-jobs-manager
  apiGroup: rbac.authorization.k8s.io