apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
{{ include "build-tomo-js.labels" . | indent 4 }}
stringData:
  GITHUB_SECRET: {{ default "not set" .Values.githubSecret }}
  DOCKER_TOKEN:  {{ default "not set" .Values.dockerToken }}
  DOCKER_USER:   {{ default "not set" .Values.dockerUser }}
