{{ if .Values.credentials.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
{{ include "build-tomo.labels" . | indent 4 }}
stringData:
{{ with .Values.credentials.secret }}
  GITHUB_SECRET: {{ default "not set" .githubSecret }}
  DOCKER_TOKEN:  {{ default "not set" .dockerToken }}
  DOCKER_USER:   {{ default "not set" .dockerUser }}
{{ end }}
{{ end }}