apiVersion: v1
kind: Service
metadata:
  name: {{ include "build-tomo-js.fullname" . }}
  labels:
    {{- include "build-tomo-js.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nodejs
      protocol: TCP
      name: nodejs
  selector:
    {{- include "build-tomo-js.selectorLabels" . | nindent 4 }}
